### ISSUE TITLE
здраствуйте

### ISSUE THREAD

**Issue by kiraventom** [aleasper/film-threads-front#1]
здраствуйте а как включить ваш проэкт
спасибо
 
 
 
___________________________________
_програмирование это жизнь.._

**Comment by aleasper** [comment]
kiraventom, здравствуйте!
Текущие инструкции для запуска в "dev" версии в README.MD. Готовый вариант будет доступен позже, после защиты диплома

**Comment by kiraventom** [comment]
спсибо 🥺
